# GitHub Sponsors & Project Funding Configuration
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Official GitHub Sponsors username
github: [mohxmd]

# Custom donation platforms
custom: ['https://paypal.me/zerathlabs']

