/* auto-generated by NAPI-RS */
/* eslint-disable */
/** High-level client for communicating with thermal receipt printers. */
export declare class Printer {
  /** Creates a printer connecting over TCP / Ethernet / Wi-Fi. */
  static tcp(address: string, dialect?: string | undefined | null): Printer
  /** Creates a printer connecting over Serial / RS-232 / Virtual COM. */
  static serial(port: string, baudRate?: number | undefined | null, dialect?: string | undefined | null): Printer
  /** Creates a printer connecting over direct USB (Printer Class 07). */
  static usb(vendorId: number, productId: number, dialect?: string | undefined | null): Printer
  /** Creates an in-memory mock printer for testing without physical hardware. */
  static mock(dialect?: string | undefined | null): Printer
  /** Transmits receipt commands to the target printer. */
  print(receipt: Receipt): Promise<NapiResult<undefined>>
  /** Queries real-time hardware status and sensor telemetry. */
  queryStatus(): Promise<NapiResult<JsPrinterStatus>>
  /** Returns the accumulated binary wire bytes written to an in-memory mock printer. */
  getRecordedBytes(): Promise<NapiResult<Buffer | undefined | null>>
}
export type JsPrinter = Printer

/** A receipt builder for thermal printers. */
export declare class Receipt {
  /**
   * Creates a new receipt builder.
   *
   * @param paperWidth - Paper width: "80mm" (default) or "58mm".
   */
  constructor(paperWidth?: string | undefined | null)
  /** Initializes printer hardware state (clears formatting, resets modes). */
  init(): this
  /** Prints text without trailing newline. */
  text(text: string): this
  /** Prints text followed by a line feed. */
  textLn(text: string): this
  /** Aligns subsequent output to the left. */
  left(): this
  /** Centers subsequent output. */
  center(): this
  /** Aligns subsequent output to the right. */
  right(): this
  /** Enables or disables bold text emphasis. */
  bold(enable: boolean): this
  /** Enables or disables single underline. */
  underline(enable: boolean): this
  /** Enables or disables inverted (white-on-black) printing. */
  invert(enable: boolean): this
  /** Enables or disables double-height characters. */
  doubleHeight(enable: boolean): this
  /** Enables or disables double-width characters. */
  doubleWidth(enable: boolean): this
  /** Enables or disables both double-height and double-width characters. */
  doubleSize(enable: boolean): this
  /** Feeds paper by the specified number of lines. */
  feed(lines?: number | undefined | null): this
  /** Performs a full paper cut. */
  cutFull(): this
  /** Performs a partial paper cut. */
  cutPartial(): this
  /** Prints a full horizontal divider line spanning paper width. */
  divider(ch?: string | undefined | null): this
  /** Prints a double-line horizontal divider rule (`================`). */
  dividerDouble(): this
  /** Prints a dotted horizontal divider rule (`................`). */
  dividerDotted(): this
  /** Prints a dashed horizontal divider rule (`- - - - - - - - `). */
  dividerDashed(): this
  /** Prints a repeating pattern horizontal divider rule across paper width. */
  dividerPattern(pattern: string): this
  /** Prints a 2-column row (left aligned left, right aligned right). */
  twoColumn(left: string, right: string): this
  /** Prints a 3-column row (left, center, right). */
  threeColumn(left: string, center: string, right: string): this
  /** Configures active table columns and prints a bold header row. */
  tableHeader(headers: Array<string>, columns: Array<TableColumnOptions>): this
  /** Sets active table columns without printing a header row. */
  setColumns(columns: Array<TableColumnOptions>): this
  /** Prints a table row formatted against the configured table columns. */
  row(cells: Array<string>): this
  /** Clears any configured table columns. */
  clearColumns(): this
  /** Prints a QR code with the given content. */
  qr(content: string): this
  /** Appends a ZATCA (Saudi Arabia) & FTA (UAE) compliant E-Invoicing QR code. */
  zatcaQr(invoice: JsZatcaInvoice): this
  /** Prints a Code128 barcode. */
  barcode128(content: string): this
  /** Triggers acoustic buzzer alert. */
  beep(count?: number | undefined | null, duration?: number | undefined | null): this
  /** Triggers cash drawer kickout pin. */
  openDrawer(): this
  /** Renders a virtual SVG vector graphic preview of the receipt. */
  renderSvg(): string
  /** Renders a responsive HTML component snippet preview of the receipt. */
  renderHtml(): string
  /**
   * Encodes receipt commands into raw binary wire bytes for the given dialect.
   *
   * @param dialect - "escpos" (default) or "star".
   */
  encode(dialect?: string | undefined | null): NapiResult<Buffer>
}

export type JsReceipt = Receipt

/** Enumerates available serial / COM ports on the host system. */
export declare function availablePorts(): NapiResult<Array<string>>

/** Real-time printer sensor telemetry and mechanical status. */
export interface JsPrinterStatus {
  isOnline: boolean
  isReady: boolean
  paper: string
  cover: string
  drawer: string
  cutterError: boolean
  headOverheated: boolean
}

/** Metadata for an enumerated USB Printer Class device. */
export interface JsUsbPrinterInfo {
  vendorId: number
  productId: number
  serialNumber?: string
  manufacturer?: string
  productName?: string
}

/** Enumerates connected USB Printer Class (0x07) devices. */
export declare function listPrinters(): NapiResult<Array<JsUsbPrinterInfo>>

/** Configuration options for table columns. */
export interface TableColumnOptions {
  /** Fixed character width. */
  widthFixed?: number
  /** Simple fixed character width shorthand (alias for widthFixed). */
  width?: number
  /** Proportional fraction of total columns (0.0 .. 1.0). */
  widthFraction?: number
  /** Text alignment: "left", "center", or "right". */
  align?: string
  /** Text alignment alias: "left", "center", or "right" (alias for align). */
  alignment?: string
}

/** ZATCA (Saudi Arabia) & FTA (UAE) compliant invoice metadata for E-Invoicing QR codes. */
export interface JsZatcaInvoice {
  /** Seller's legal or commercial trading name (Tag 1). */
  sellerName: string
  /** Tax Registration Number (TRN / VAT number, typically 15 digits) (Tag 2). */
  vatNumber: string
  /** Invoice timestamp in ISO 8601 format (Tag 3, e.g. "2026-09-10T14:30:00Z"). */
  timestamp: string
  /** Invoice total amount including VAT (Tag 4, e.g. "115.00"). */
  totalAmount: string
  /** Total VAT amount (Tag 5, e.g. "15.00"). */
  vatAmount: string
}

/** Generates a ZATCA (Saudi Arabia) & FTA (UAE) compliant Base64 QR payload string from invoice metadata. */
export declare function zatcaQrBase64(
  sellerName: string,
  vatNumber: string,
  timestamp: string,
  totalAmount: string,
  vatAmount: string,
): string

